import Image from 'next/image';
import InputComponent from '../atoms/InputComponent';
import { ChangeEvent, use, useEffect, useState } from 'react';
import { getQrCode } from '@/server/Login';
import { toast } from 'react-toastify';
import Loader from '../atoms/Loader';
interface FUserOnboardComponentProps {
  code: string;
  setCode: (e: string) => void;
  error: string;
  userName: string;
  submitQrCode: () => void;
  handleSignOut: () => void;
}
export default function FUserOnboardComponent({
  code,
  setCode,
  error,
  userName,
  submitQrCode,
  handleSignOut,
}: FUserOnboardComponentProps) {
  const [imageSrc, setImageSrc] = useState<string>('');
  const [loader, setLoader] = useState<boolean>(true);
  const [secretKey, setSecretKey] = useState<string>('');

  async function getQrCodeImage(userName: string) {
    const response = await getQrCode(userName);
    if (response.error && response.error.length > 0) {
      response.error.forEach((err: any) => {
        toast.error('Your session has expired. Please login again.');
        handleSignOut();
      });
    } else {
      setImageSrc(response.data?.qrUri as string);
      setSecretKey(response.data?.code as string);
      setLoader(false);
    }
  }

  useEffect(() => {
    getQrCodeImage(userName);
  }, []);
  return (
    <div className="rounded-lg bg-slate-200  py-4 text-center shadow-lg md:px-20 ">
      <div>
        <p className="text-sm md:text-base font-bold text-logoColorBlue">
          Enable two-factor authentication
        </p>
        <div className="mt-3 h-[1px] bg-slate-300" />
      </div>
      <div>
        <div className="mb-3 mt-6 rounded-lg bg-white p-5 text-start shadow-lg w-[400px] md:w-[500px]">
          <div>
            <p className=" text-sm md:text-base font-bold text-logoColorBlue">
              01- Download an Authenticator Application
            </p>
            <p className="mt-2 text-xs font-normal text-logoColorGreen">
              Download and install an authenticator application on your mobile
              device.
            </p>
            <div className="mt-7 h-[1px] bg-slate-200" />
          </div>
          <div className="mt-7">
            <p className="text-base font-bold text-logoColorBlue">
              02- Scan the QR Code
            </p>
            <p className="mt-2 text-xs font-normal text-logoColorGreen">
              Open the authenticator application and scan the QR code using your
              mobile device's camera.
            </p>
            <div className="mt-5 flex justify-center">
              {loader ? (
                <div>
                  <Loader />
                </div>
              ) : (
                <Image
                  src={imageSrc}
                  width={150}
                  height={150}
                  alt="no image available"
                />
              )}
            </div>
            <div className="mt-5">
              <p className="mt-2 text-xs font-normal text-logoColorGreen">
                Here is the Sceret Key below if you are unable to scan the QR
                code.
              </p>
              <div className="mt-1">
                <p className="max-w-md break-words text-sm font-bold text-logoColorBlue">
                  {secretKey}
                </p>
              </div>
            </div>
            <div className="mt-7 h-[1px] bg-slate-200" />
          </div>
          <div className="mt-7">
            <p className="text-base font-bold text-logoColorBlue">
              03- Login with your code
            </p>
            <div className="mt-2">
              <p className="mt-2 text-xs font-normal text-logoColorGreen">
                Enter the 6-digit code generated by the authenticator
                application.
              </p>
              <div className="mt-1">
                <InputComponent
                  label={''}
                  type={'text'}
                  placeholder={'Enter your 6-digit code here'}
                  name={'code'}
                  maxLength={6}
                  value={code}
                  className="w-10/12"
                  onChange={(e: ChangeEvent<HTMLInputElement>) => {
                    const { value } = e.target;
                    const code = value.replace(/[^0-9]/g, '');
                    setCode(e.target.value);
                  }}
                  error={error}
                />
              </div>
              <div className="mt-12 flex justify-center">
                <button
                  onClick={submitQrCode}
                  className="w-1/2 rounded-xl bg-gradient-to-r from-logoColorGreen to-logoColorBlue py-3 text-base text-white"
                >
                  Verify Code
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
